name: flutter_fleurette
description: Une application qui reconnait le text à partir d'une image.
publish_to: 'je sais pas'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  camera: ^0.10.0+4
  flutter:
    sdk: flutter
  google_ml_kit: ^0.16.3
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.2.0
  google_mlkit_translation: ^0.9.0
  translator: ^0.1.7
  share: ^2.0.4
  image_picker: ^1.0.7

  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  animated_splash_screen: 1.3.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  

flutter_icons:
  android: true
  ios: true




